// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PenelopeSMS.Infrastructure.SqlServer;

#nullable disable

namespace PenelopeSMS.Infrastructure.SqlServer.Migrations
{
    [DbContext(typeof(PenelopeSmsDbContext))]
    [Migration("20260312221801_InitialImportSchema")]
    partial class InitialImportSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PenelopeSMS.Domain.Entities.CustomerPhoneLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustSid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhoneNumberRecordId")
                        .HasColumnType("int");

                    b.Property<string>("RawPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("PhoneNumberRecordId");

                    b.HasIndex("CustSid", "PhoneNumberRecordId")
                        .IsUnique();

                    b.ToTable("CustomerPhoneLinks", (string)null);
                });

            modelBuilder.Entity("PenelopeSMS.Domain.Entities.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RowsImported")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("RowsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("RowsRejected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("ImportBatches", (string)null);
                });

            modelBuilder.Entity("PenelopeSMS.Domain.Entities.PhoneNumberRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CanonicalPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalPhoneNumber")
                        .IsUnique();

                    b.ToTable("PhoneNumberRecords", (string)null);
                });

            modelBuilder.Entity("PenelopeSMS.Domain.Entities.CustomerPhoneLink", b =>
                {
                    b.HasOne("PenelopeSMS.Domain.Entities.ImportBatch", "ImportBatch")
                        .WithMany("CustomerPhoneLinks")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PenelopeSMS.Domain.Entities.PhoneNumberRecord", "PhoneNumberRecord")
                        .WithMany("CustomerPhoneLinks")
                        .HasForeignKey("PhoneNumberRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");

                    b.Navigation("PhoneNumberRecord");
                });

            modelBuilder.Entity("PenelopeSMS.Domain.Entities.ImportBatch", b =>
                {
                    b.Navigation("CustomerPhoneLinks");
                });

            modelBuilder.Entity("PenelopeSMS.Domain.Entities.PhoneNumberRecord", b =>
                {
                    b.Navigation("CustomerPhoneLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
