// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PenelopeSMS.Infrastructure.SqlServer;

#nullable disable

namespace PenelopeSMS.Infrastructure.SqlServer.Migrations
{
    [DbContext(typeof(PenelopeSmsDbContext))]
    [Migration("20260312233420_AddCampaignExecutionSchema")]
    partial class AddCampaignExecutionSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PenelopeSMS.Domain.Entities.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatchSize")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TemplateBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateFilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.ToTable("Campaigns", (string)null);
                });

            modelBuilder.Entity("PenelopeSMS.Domain.Entities.CampaignRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("InitialTwilioStatus")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("LastAttemptedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhoneNumberRecordId")
                        .HasColumnType("int");

                    b.Property<string>("ProviderErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProviderErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TwilioMessageSid")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumberRecordId");

                    b.HasIndex("CampaignId", "PhoneNumberRecordId")
                        .IsUnique();

                    b.ToTable("CampaignRecipients", (string)null);
                });

            modelBuilder.Entity("PenelopeSMS.Domain.Entities.CustomerPhoneLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustSid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhoneNumberRecordId")
                        .HasColumnType("int");

                    b.Property<string>("RawPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("PhoneNumberRecordId");

                    b.HasIndex("CustSid", "PhoneNumberRecordId")
                        .IsUnique();

                    b.ToTable("CustomerPhoneLinks", (string)null);
                });

            modelBuilder.Entity("PenelopeSMS.Domain.Entities.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("RowsImported")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("RowsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("RowsRejected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("ImportBatches", (string)null);
                });

            modelBuilder.Entity("PenelopeSMS.Domain.Entities.PhoneNumberRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampaignEligibilityStatus")
                        .HasColumnType("int");

                    b.Property<string>("CanonicalPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EligibilityEvaluatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnrichmentFailureStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastEnrichedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastEnrichmentAttemptedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastEnrichmentErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("LastEnrichmentErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime?>("LastEnrichmentFailedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TwilioCarrierName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TwilioCountryCode")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("TwilioLineType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TwilioLookupPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwilioMobileCountryCode")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("TwilioMobileNetworkCode")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalPhoneNumber")
                        .IsUnique();

                    b.ToTable("PhoneNumberRecords", (string)null);
                });

            modelBuilder.Entity("PenelopeSMS.Domain.Entities.CampaignRecipient", b =>
                {
                    b.HasOne("PenelopeSMS.Domain.Entities.Campaign", "Campaign")
                        .WithMany("Recipients")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PenelopeSMS.Domain.Entities.PhoneNumberRecord", "PhoneNumberRecord")
                        .WithMany("CampaignRecipients")
                        .HasForeignKey("PhoneNumberRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("PhoneNumberRecord");
                });

            modelBuilder.Entity("PenelopeSMS.Domain.Entities.CustomerPhoneLink", b =>
                {
                    b.HasOne("PenelopeSMS.Domain.Entities.ImportBatch", "ImportBatch")
                        .WithMany("CustomerPhoneLinks")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PenelopeSMS.Domain.Entities.PhoneNumberRecord", "PhoneNumberRecord")
                        .WithMany("CustomerPhoneLinks")
                        .HasForeignKey("PhoneNumberRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");

                    b.Navigation("PhoneNumberRecord");
                });

            modelBuilder.Entity("PenelopeSMS.Domain.Entities.Campaign", b =>
                {
                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("PenelopeSMS.Domain.Entities.ImportBatch", b =>
                {
                    b.Navigation("CustomerPhoneLinks");
                });

            modelBuilder.Entity("PenelopeSMS.Domain.Entities.PhoneNumberRecord", b =>
                {
                    b.Navigation("CampaignRecipients");

                    b.Navigation("CustomerPhoneLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
